=== AndreyKakura/task3-xml/src/main/resources/candies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/candies"
        xmlns:tns="http://www.example.com/candies"
        elementFormDefault="qualified">
    <element name="candies">
        <complexType>
            <sequence>
                <element name="candy" type="tns:Candy" minOccurs="1" maxOccurs="100"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Candy">
        <sequence>
            <element name="energy" type="int"/>
            <element name="type" type="string"/>
            <element name="ingredients" type="tns:Ingredients"/>
            <element name="value" type="tns:Value"/>
            <element name="production" type="string"/>
            <element name="filling" type="boolean" minOccurs="0"/>
        </sequence>
        <attribute name="id" use="required" type="long"/>
        <attribute name="name" use="required" type="string"/>
        <attribute name="expiration-date" use="optional"/>
    </complexType>
    <complexType name="Value">
        <sequence>
            <element name="proteins" type="int"/>
            <element name="fats" type="int"/>
            <element name="carbohydrates" type="int"/>
        </sequence>
    </complexType>
    <complexType name="Ingredient">
        <attribute name="name" use="required"/>
        <attribute name="quantity" use="optional" default="1"/>
    </complexType>
    <complexType name="Ingredients">
        <sequence>
            <element name="ingredient" type="tns:Ingredient" minOccurs="1" maxOccurs="100"/>
        </sequence>
    </complexType>
</schema>

=== AndreyKakura/task3-xml/src/main/resources/candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/candies"
          xsi:schemaLocation="http://www.example.com/candies candies.xsd">
    <candy id="101" name="Alenka" expiration-date="2022-07">
        <energy>100</energy>
        <type>chocolate</type>
        <ingredients>
            <ingredient name="water"/>
            <ingredient name="sugar" quantity="10"/>
            <ingredient name="fructose" quantity="3"/>
            <ingredient name="cocoa" quantity="20"/>
            <ingredient name="vanillin" quantity="2"/>
        </ingredients>
        <value>
            <proteins>8</proteins>
            <fats>36</fats>
            <carbohydrates>52</carbohydrates>
        </value>
        <production>Red October</production>
        <filling>true</filling>
    </candy>
</candies>
